url: https://y7kim.github.io
baseurl:

# Site settings
title: Smith & Charles
email: smithandcharlesdei@gmail.com
description: "We are a black-owned diversity, equity, and inclusion consulting firm."

# Team names, titles and social links
people:
  - name: Tremaine Smith
    pic: 1
    position: Co-Founder of Smith&Charles DEI Consulting
    social:
    bio: Tremaine is a Program Coordinator for an adolescent health education program at a hospital in NYC and an independent DEI consultant with Smith&Charles.  Tremaine has a love for the intersection of identity and education. In pursuing his interests, he has coordinated and sat on panels for diversity in America and abroad.

  - name: Daphne Charles
    pic: 2
    position: Co-Founder of Smith&Charles DEI Consulting
    social:
    bio: Daphne Charles is a diversity, equity, and inclusion consultant with Smith & Charles as well as a Software Engineer at American Express. She holds a Masters Degree in Information Science and a Bachelors degree in Information Technology from Rutgers University. As a DEI consultant, she specializes in helping women and people of color break into the tech industry through tailored mentoring services and career coaching.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
